version: '3'
services:
  app:
    container_name: torotutor-app
    restart: always
    build: .
    depends_on:
        - mongodb
    ports:
      - '80:3000'
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'